// Enhanced ChatSummary Schema with comprehensive emotional tone values
const mongoose = require("mongoose");
const { Schema } = mongoose;

const chatSummarySchema = new Schema({
  chatSession: {
    type: Schema.Types.ObjectId,
    ref: "ChatSession",
    required: true,
    unique: true,
  },
  summaryText: {
    type: String,
    required: true,
  },
  keyTopics: [
    {
      type: String,
      trim: true,
    },
  ],
  emotionalTone: {
    type: String,
    enum: [
      // Basic Emotions
      "positive",
      "negative",
      "neutral",
      "mixed",

      // Anxiety & Stress Related
      "anxious",
      "worried",
      "stressed",
      "overwhelmed",
      "panicked",
      "nervous",
      "tense",

      // Depression & Sadness Related
      "depressed",
      "sad",
      "melancholy",
      "grief",
      "disappointed",
      "hopeless",
      "empty",
      "numb",

      // Anger & Frustration Related
      "angry",
      "frustrated",
      "irritated",
      "resentful",
      "bitter",
      "annoyed",

      // Fear & Insecurity Related
      "fearful",
      "insecure",
      "vulnerable",
      "uncertain",
      "doubtful",
      "apprehensive",

      // Positive & Hope Related
      "hopeful",
      "optimistic",
      "grateful",
      "relieved",
      "content",
      "peaceful",
      "joyful",
      "excited",
      "motivated",
      "confident",
      "proud",
      "accomplished",

      // Calm & Stable
      "calm",
      "stable",
      "centered",
      "balanced",
      "serene",

      // Social & Relationship Related
      "lonely",
      "isolated",
      "rejected",
      "misunderstood",
      "supported",
      "connected",
      "loved",

      // Energy & Motivation Related
      "energetic",
      "tired",
      "exhausted",
      "drained",
      "burnout",
      "apathetic",
      "motivated",
      "inspired",

      // Confusion & Clarity Related
      "confused",
      "conflicted",
      "indecisive",
      "clear",
      "focused",
      "determined",

      // Trauma & Recovery Related
      "traumatized",
      "healing",
      "recovering",
      "resilient",
      "empowered",

      // Self-Worth Related
      "worthless",
      "inadequate",
      "guilty",
      "shameful",
      "self-critical",
      "self-compassionate",
      "accepting",

      // Crisis & Emergency Related
      "crisis",
      "suicidal",
      "self-harm",
      "dangerous",

      // Breakthrough & Progress Related
      "breakthrough",
      "enlightened",
      "transformed",
      "growing",
      "learning",
    ],
    trim: true,
  },
  // Optional: Add intensity and secondary emotions
  emotionalIntensity: {
    type: Number,
    min: 1,
    max: 10,
    default: 5,
  },
  secondaryEmotions: [
    {
      type: String,
      enum: [
        // Same enum values as emotionalTone
        "positive",
        "negative",
        "neutral",
        "mixed",
        "anxious",
        "worried",
        "stressed",
        "overwhelmed",
        "panicked",
        "nervous",
        "tense",
        "depressed",
        "sad",
        "melancholy",
        "grief",
        "disappointed",
        "hopeless",
        "empty",
        "numb",
        "angry",
        "frustrated",
        "irritated",
        "resentful",
        "bitter",
        "annoyed",
        "fearful",
        "insecure",
        "vulnerable",
        "uncertain",
        "doubtful",
        "apprehensive",
        "hopeful",
        "optimistic",
        "grateful",
        "relieved",
        "content",
        "peaceful",
        "joyful",
        "excited",
        "motivated",
        "confident",
        "proud",
        "accomplished",
        "calm",
        "stable",
        "centered",
        "balanced",
        "serene",
        "lonely",
        "isolated",
        "rejected",
        "misunderstood",
        "supported",
        "connected",
        "loved",
        "energetic",
        "tired",
        "exhausted",
        "drained",
        "burnout",
        "apathetic",
        "inspired",
        "confused",
        "conflicted",
        "indecisive",
        "clear",
        "focused",
        "determined",
        "traumatized",
        "healing",
        "recovering",
        "resilient",
        "empowered",
        "worthless",
        "inadequate",
        "guilty",
        "shameful",
        "self-critical",
        "self-compassionate",
        "accepting",
        "crisis",
        "suicidal",
        "self-harm",
        "dangerous",
        "breakthrough",
        "enlightened",
        "transformed",
        "growing",
        "learning",
      ],
    },
  ],
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

const ChatSummary = mongoose.model("ChatSummary", chatSummarySchema);
module.exports = ChatSummary;
